args_map:
  log_dir: train.log_dir
  seed: train.seed
  use_train_subset: data.use_train_subset
  use_train_repeat: data.use_train_repeat
  use_val_subset: data.use_val_subset
  use_initiate: train.use_initiate
  batch_size: data.batch_size
  gradient_accumulate: data.gradient_accumulate
  epochs: train.epochs
  lr: train.learning_rate
  mul_lr: train.mul_learning_rate
  num_codes: model.autoencoder.params.quantize.params.n_e
  enterpoint: train.enterpoint
  code_path: train.code_path
  embed_path: train.embed_path
  mode: mode
mode: train
use_amp: false
train:
  epochs: 100
  seed: 42
  learning_rate: 4.5e-6
  mul_learning_rate: 1.0
  weight_decay: 0.05
  visualize_interval: 50
  pipeline: ae # ae / ae_disc
  enterpoint: null
  code_path: null
  use_initiate: random_select
  embed_path: null
  nnodes: 1
data:
  preprocess: plain
  batch_size: 1024
  test_batch_size: 1024
  gen_embed_batch_size: 1024
  gradient_accumulate: 1
  use_train_subset: null
  use_train_repeat: null
  use_val_subset: null
  train:
    target: torchvision.datasets.CIFAR10
    params:
      root: /home/zbr/disk1/datasets/cifar10/
      download: true
      train: true
      transform: 
        target: optvq.data.preprocessor.plain_preprocessor
        params:
          resize: 32
  val:
    target: torchvision.datasets.CIFAR10
    params:
      root: /home/zbr/disk1/datasets/cifar10/
      download: true
      train: false
      transform: 
        target: optvq.data.preprocessor.plain_preprocessor
        params:
          resize: 32
model:
  autoencoder:
    target: optvq.models.vqgan.VQModel
    params:
      use_connector: true
      encoder:
        target: optvq.models.backbone.simple_cnn.PlainCNNEncoder
        params:
          in_dim: 3
      decoder:
        target: optvq.models.backbone.simple_cnn.PlainCNNDecoder
        params:
          out_dim: 3
      quantize:
        target: optvq.models.quantizer.VectorQuantizer
        params:
          n_e: 1024
          e_dim: 8
          beta: 0.25
          use_proj: true
          fix_codes: false
          start_quantize_steps: null
          num_head: 1
      loss:
        target: optvq.losses.aeloss.AELoss
        params:
          loss_l1_weight: 1.0
          loss_l2_weight: 1.0
          loss_p_weight: 0.0
          loss_q_weight: 1.0
